[package]
name = "stracciatella"
version = "0.1.0"
authors = ["Stefan Lau <github@stefanlau.com>"]

[dependencies]
getopts = "0.2.15"
serde = "1"
serde_derive = "1"
serde_json = "1"

[dev-dependencies]
regex = "0.1"
tempdir = "0.3"
